baseURL: https://www.sheleshgupta.com
title: Shelesh Gupta
paginate: 5
theme: shelesh
 
# menu:
#     main:
#         - name: Contact
#           url: /contact/
#           weight: 30
        # - name: Articles
        #   url: /articles/
        #   weight: 20
        # - name: Projects
        #   url: /projects/
        #   weight: 15

     # - name: Categories
        #   url: /categories/
        #   weight: 10
        # - name: new Tab
        #   url: /newtab/
        #   weight: defines order of tabs
   


params:
    author: Shelesh Gupta
    defaultTheme: dark
    disableThemeToggle: false
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true

    profileMode:
        # Disable to populate home page with 'mainSections' content
        enabled: true
        title:  Hello, I'm Shelesh Gupta ðŸ‘‹
        description: | 
          Experienced Cyber Securty Executive.

          Managing Director, Accenture Security SEA.
        imageUrl: "/images/profile.png"
        imageTitle: Shelesh Gupta
        imageWidth: 250
        imageHeight: 250
#        buttons:
#            - name: Don't click me
#              url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
    mainSections:
      - articles

    socialIcons:
        - name: twitter
          url: "https://twitter.com/sheleshgupta"
        - name: github
          url: "https://github.com/sheleshgupta"
        - name: linkedin
          url: "https://www.linkedin.com/in/shelesh-gupta-a4a594a/"

      # add more social icons. find more in svg.html file
      # - name: youtube
      #   url: yoururl
      # - name: twitter
      #   url: yoururl
      # - name: facebook
      #   url: yoururl


    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "/images/favicon.ico"
          favicon16x16: "/images/favicon-16x16.png"
          favicon32x32: "/images/favicon-32x32.png"
          apple_touch_icon: "/images/apple-touch-icon.png"
          safari_pinned_tab: "/images/apple-touch-icon.png"
enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true

